import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE
} from '@/constants/navigation.constant'

import type { NavigationTree } from '@/@types/navigation'

const navigationConfig: NavigationTree[] = [
    {
        key: 'peopleManagement',
        path: '',
        title: 'مدیریت افراد',
        translateKey: 'nav.peopleManagement',
        icon: 'users',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'patients',
                path: '/patients',
                title: 'مدیریت بیماران',
                translateKey: 'nav.patients',
                icon: 'user-group',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'patientPresenter',
                path: '/patient-presenter',
                title: 'مدیریت معرف بیمار (بزودی)',
                translateKey: 'nav.patientPresenter',
                icon: 'user-plus',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'benefactors',
                path: '/benefactors',
                title: 'مدیریت افراد خیر',
                translateKey: 'nav.benefactors',
                icon: 'heart',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'healthAssists',
                path: '/health-assists',
                title: 'مدیریت سلامت‌یاران',
                translateKey: 'nav.healthAssists',
                icon: 'health',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'doctors',
                path: '/doctors',
                title: 'مدیریت پزشکان',
                translateKey: 'nav.doctors',
                icon: 'stethoscope',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            }
        ],
    },
    {
        key: 'organizationManagement',
        path: '',
        title: 'مدیریت سازمان‌ها',
        translateKey: 'nav.organizationManagement',
        icon: 'building',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'privateCompanies',
                path: '/private-companies',
                title: 'مدیریت شرکت‌های خصوصی',
                translateKey: 'nav.privateCompanies',
                icon: 'building',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'medicalCenters',
                path: '/medical-centers',
                title: 'مراکز درمانی',
                translateKey: 'nav.medicalCenters',
                icon: 'activity',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'serviceCenters',
                path: '/service-centers',
                title: 'مراکز خدمات',
                translateKey: 'nav.serviceCenters',
                icon: 'tool',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'charityCenters',
                path: '/charity-centers',
                title: 'مراکز نیکوکاری',
                translateKey: 'nav.charityCenters',
                icon: 'gift',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'governmentOrganizations',
                path: '/government-organizations',
                title: 'سازمان‌های دولتی',
                translateKey: 'nav.governmentOrganizations',
                icon: 'briefcase',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'associations',
                path: '/associations',
                title: 'تشکل‌ها',
                translateKey: 'nav.associations',
                icon: 'users',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            }
        ],
    },
    {
        key: 'requestsManagement',
        path: '',
        title: 'مدیریت درخواست‌ها',
        translateKey: 'nav.requestsManagement',
        icon: 'clipboard-list',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'patientServiceRequests',
                path: '/patient-service-requests',
                title: 'درخواست‌های سرویس بیمار',
                translateKey: 'nav.patientServiceRequests',
                icon: 'service',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'consultationRequests',
                path: '/consultation-requests',
                title: 'درخواست‌های مشاوره',
                translateKey: 'nav.consultationRequests',
                icon: 'message-circle',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            }
        ],
    },
    // {
    //     key: 'home',
    //     path: '/home',
    //     title: 'Home',
    //     translateKey: 'nav.home',
    //     icon: 'home',
    //     type: NAV_ITEM_TYPE_ITEM,
    //     authority: [],
    //     subMenu: [],
    // },
    /** Example purpose only, please remove */
    // {
    //     key: 'singleMenuItem',
    //     path: '/single-menu-view',
    //     title: 'Single menu item',
    //     translateKey: 'nav.singleMenuItem',
    //     icon: 'singleMenu',
    //     type: NAV_ITEM_TYPE_ITEM,
    //     authority: [],
    //     subMenu: [],
    // },
    // {
    //     key: 'collapseMenu',
    //     path: '',
    //     title: 'Collapse Menu',
    //     translateKey: 'nav.collapseMenu.collapseMenu',
    //     icon: 'collapseMenu',
    //     type: NAV_ITEM_TYPE_COLLAPSE,
    //     authority: [],
    //     subMenu: [
    //         {
    //             key: 'collapseMenu.item1',
    //             path: '/collapse-menu-item-view-1',
    //             title: 'Collapse menu item 1',
    //             translateKey: 'nav.collapseMenu.item1',
    //             icon: '',
    //             type: NAV_ITEM_TYPE_ITEM,
    //             authority: [],
    //             subMenu: [],
    //         },
    //         {
    //             key: 'collapseMenu.item2',
    //             path: '/collapse-menu-item-view-2',
    //             title: 'Collapse menu item 2',
    //             translateKey: 'nav.collapseMenu.item2',
    //             icon: '',
    //             type: NAV_ITEM_TYPE_ITEM,
    //             authority: [],
    //             subMenu: [],
    //         },
    //     ],
    // },
    // {
    //     key: 'groupMenu',
    //     path: '',
    //     title: 'Group Menu',
    //     translateKey: 'nav.groupMenu.groupMenu',
    //     icon: 'groupMenu',
    //     type: NAV_ITEM_TYPE_TITLE,
    //     authority: [],
    //     subMenu: [
    //         {
    //             key: 'groupMenu.single',
    //             path: '/group-single-menu-item-view',
    //             title: 'Group single menu item',
    //             translateKey: 'nav.groupMenu.single',
    //             icon: 'groupSingleMenu',
    //             type: NAV_ITEM_TYPE_ITEM,
    //             authority: [],
    //             subMenu: [],
    //         },
    //         {
    //             key: 'groupMenu.collapse',
    //             path: '',
    //             title: 'Group collapse menu',
    //             translateKey: 'nav.groupMenu.collapse.collapse',
    //             icon: 'groupCollapseMenu',
    //             type: NAV_ITEM_TYPE_COLLAPSE,
    //             authority: [],
    //             subMenu: [
    //                 {
    //                     key: 'groupMenu.collapse.item1',
    //                     path: '/group-collapse-menu-item-view-1',
    //                     title: 'Menu item 1',
    //                     translateKey: 'nav.groupMenu.collapse.item1',
    //                     icon: '',
    //                     type: NAV_ITEM_TYPE_ITEM,
    //                     authority: [],
    //                     subMenu: [],
    //                 },
    //                 {
    //                     key: 'groupMenu.collapse.item2',
    //                     path: '/group-collapse-menu-item-view-2',
    //                     title: 'Menu item 2',
    //                     translateKey: 'nav.groupMenu.collapse.item2',
    //                     icon: '',
    //                     type: NAV_ITEM_TYPE_ITEM,
    //                     authority: [],
    //                     subMenu: [],
    //                 },
    //             ],
    //         },
    //     ],
    // },
]

export default navigationConfig